# Generated by Django 5.0.6 on 2024-08-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
