# Generated by Django 5.0.6 on 2024-08-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_card', '0002_alter_person_created_alter_person_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_of_birth',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_of_death',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
