# Generated by Django 5.0.6 on 2024-08-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_card', '0003_alter_person_created_alter_person_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date_of_death',
            field=models.DateField(blank=True, null=True),
        ),
    ]
