# Generated by Django 5.0.6 on 2024-08-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_card', '0005_alter_person_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profile_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
